### ISSUE TITLE
Items from a chest get deleted after sorting

### ISSUE THREAD

**Issue by MineB00m** [GregTechCE/GregTech#1043]
I'm running GTCE 1.9.0.481 on SpongeForge 7.1.7-RC3924, and after pressing a sort button in any chest, there is a chance, that items in it will get deleted. Seems like it works with any chest, that supports an auto sorting feature.

**Comment by ct-klein** [comment]
Also happens on Forge 14.23.5.2847, installed part of Infitech3 pack.  Seems pretty consistent, sorted 5 steel GTCE chests, all 5 lost their contents.  Rebooted client to prove out that it wasn't just a visual glitch.

**Comment by LAGIdiot** [comment]
**Version:**
1.9.1 (dev build on 853ffbc44a239df957fbe4a434f2733810253e41)

**Environment:**
GTCE dev; new world generated

**Setup:**
Chest (Wooden & Steel) with various items (vanilla/modded, with/without damage, with/without NBT, with/without metadata, nonstackable/stackable).

**Outcome:**
Unable to reproduce. Fixed by https://github.com/GregTechCE/GregTech/commit/fcf2560280cd35dc7bf72079ac4ae3211e9bd29e#diff-e37391b19981fdbb9f297b392aba2fb0R727.

**Proposition:**
Close as fixed

**Comment by PinkHairedBoi** [comment]
Version: 1.9.1, forge 2847.
**Still happens.**
**Steps to reproduce:**
Place MULTIPLE STACKS of one item and split it into different cells.
Click Sort - and say good bye to your items.

Looks like multiple cells find first cell to unite with, then trying to unite all together in it, but after first reaches 64 items stack sorted, cell becomes empty, and next stack trying to unite with empty cell - NullPointerException.

**Comment by LAGIdiot** [comment]
@PinkHairedBoi please provide full version (especially build number).

**Comment by PinkHairedBoi** [comment]
> @PinkHairedBoi please provide full version (especially build number).

ye sorry, a bit missed, not 1.9.1, but still after fix you mentioned.

**Forge 14.23.5.2847**
**gregtech-1.12.2-1.9.0.481**

**Comment by LAGIdiot** [comment]
I retested again on 1.9.1 (dev build on 3bfb9c4a87a8e19b7ec75afb690c1dc530a3539a) and it is **fixed**. But build on which it is working as expected is not yet available for public.

**Comment by PinkHairedBoi** [comment]
> I retested again, this time on 1.9.1 (dev build on [3bfb9c4](https://github.com/GregTechCE/GregTech/commit/3bfb9c4a87a8e19b7ec75afb690c1dc530a3539a)) and it is **fixed**. But build on which it is working as expected is not yet available for public.

Thanks, awaiting.

**Comment by LAGIdiot** [comment]
Fix for this issue was already release. Please upgrade GTCE to version 1.9.1.505 or newer to take advantage of that fix.
